asbamboo\qirifu\common\model\sysDbLog\Entity:
  type: entity
  table: t_sys_db_log
  id:
    seq:
      type: integer
      options:
        unsigned: true
        comment: '序号'
      generator:
        strategy: AUTO
  fields:
    request_url:
      type: string
      length: 255
      nullable: false
      options: 
        default: ''
        comment: '请求url'
    table:
      type: string
      length: 45
      nullable: false
      options: 
        default: ''
        comment: '操作的表'
      column: table_name
    uniqid:
      type: string
      length: 255
      nullable: false
      options: 
        default: ''
        comment: '操作数据行的唯一标识'
    data:
      type: array
      nullable: true
      options: 
        comment: '所修改的数据信息'
    request_info:
      type: array
      nullable: true
      options: 
        comment: '请求信息'
    create_time:
      type: integer
      nullable: false
      options:
        default: '0'
        unsigned: true
        comment: '添加时间'
    create_user:
      type: string
      length: 13
      nullable: false
      options:
        fixed: true
        default: ''
        comment: '添加人id'
    create_ip:
      type: string
      length: 45
      nullable: false
      options:
        fixed: true
        default: ''
        comment: '添加人ip'
    version:
      type: smallint
      version: true
      options:
        unsigned: true      
        default: '0'